### ISSUE TITLE
MovementHandler being called improperly

### ISSUE THREAD

**Issue by zappybiby** [ajchili/BomberCrewBot#8] opened 2017-11-30 03:26 UTC
MovementHandler is being called due to incorrect matches being made by `matchTemplate()`

[Line 39 of findobjectives.py](https://github.com/ajchili/BomberCrewBot/blob/c8a215420885daa7c13ebe8743315bf13d90552a/findobjectives.py#L39)
This could also be due to lines 9 - 12 of [findobjectives.py](https://github.com/ajchili/BomberCrewBot/blob/c8a215420885daa7c13ebe8743315bf13d90552a/findobjectives.py)

**Comment by ajchili** [comment] 2017-12-03 05:06
A system needs to be created to suspend navigation search when the nav icon is not present.

**Comment by ajchili** [comment] 2017-12-05 02:25
A fix for this would be to look if the navigator has found the next point. This can be done by determining if [this](http://prntscr.com/hj6110) bar is filled completely with the green progress bar.

I am currently having issues getting the right color. opencv2 does not seem to want to get the right location.

```
x = int(width * 0.375)
y = int(height * 0.89)
print(window[x, y])
```

This should get the location close to the edge of the progress bar. However, it does not.

**Comment by zappybiby** [comment] 2017-12-05 23:20
The middle icon turns green when the nav point is created. 
![nav_center](https://user-images.githubusercontent.com/15076478/33631299-2b8a6c56-d9d8-11e7-9d7e-58c478e45952.PNG)

Color of inner circle is between #327C4B and #4E8E64
**Converted to OpenCV HSV**: [70, 152, 124] and [70, 115, 142]

To minimize performance hit, we should set the ROI to only the inner part of the nav display. 

If a user uses a different resolution the UI will scale accordingly. Although the center of the circle can be predicted by just dividing the original width/height by the new width/height, this will not consider the change to the inner circle's diameter. If the diameter of the inner circle is not accounted for, the ROI may unintentionally include the outer ring that might confuse the bot. Therefore we need to come up with an equation that will scale the diameter accordingly.
```
In 1600x1024 resolution, the center of the inner circle is (618, 941).

In 1680x1050 resolution, the diameter is about 36px
In 1600x1024 resolution, the diameter is about 35px.
In 1600x900 (Note: Window is actually 1600x1000) resolution, the diameter is about 35px
In 1440x900 resolution, the diameter is about 32px
In 1280x800 resolution, the diameter is about 28px
In 720x480  (Note: Window is actually 720x450) resolution, the diameter is about 15px
```

If we considered all of these resolutions and did NOT correct the 1600x900 and 720x480 windows that have different client resolutions than their stated resolution on the title screen, [the equation](https://www.wolframalpha.com/input/?i=fit+(1680,+1050,+36),+(1600,+1024,+35),+(1600,+900,+35),+(1440,+900,+32),+(1280,+800,+28),+(720,+480,+15)) for diameter would be:
`(0.0231535 * width) - (0.00140146 * height) - 0.735615`

If we considered all of these resolutions and adjusted the resolutions to all match their actual client window (ignores the window title and the close/minimize windows at the top right), [the equation](https://www.wolframalpha.com/input/?i=fit+(1680,+1050,+36),+(1600,+1024,+35),+(1600,+1000,+35),+(1440,+900,+32),+(1280,+800,+28),+(720,+480,+15)) for diameter would be:
`(0.0282842 * width) - (0.00985191 * height) - 0.427146`

If we only considered 1600x1024, 1440x900, 1280x800, and 720x450 resolutions, [the equation](https://www.wolframalpha.com/input/?i=fit+(1600,+1024,+35),+(1440,+900,+32),+(1280,+800,+28),+(720,+450,+15)) for diameter would be:
`(0.0406095 * width) - (0.0273632 * height) - 1.95522`

I propose this method of determining if a nav point is present:
1. Press '3' to select nav dude
2. Get center of inner circle by dividing 1600 by new width and 1024 by new height. Then take the result of (1600 / (new width)) and multiply the original x center 618. Similarly, take the result of (1024 / new height) and multiply it by the original y of the center 941. 
3.  Get diameter of circle by using `(0.0406095 * width) - (0.0273632 * height) - 1.95522`
4. Get the mean of the color present in the inner circle. If this mean passes a color threshold, the nav point is present.

**Comment by ajchili** [comment] 2017-12-05 23:22
The issue is the inner circle blinks. So I am trying to get the portion of the loading indicator close to the end.

**Comment by ajchili** [comment] 2018-03-04 04:43
No longer an issue because we constantly look for the nav icon.

**Closed as completed by ajchili** 2018-03-04 04:43 UTC
Labels: p0
